apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-deploy
  namespace: argocd
  labels:
    name: demo-deploy

spec:
  project: default

  source:
    repoURL: https://github.com/victorbecerragit/argocd-demo.git
    targetRevision: HEAD
    path: yamls

    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-deploy

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true